# Generated by Django 4.1.2 on 2022-10-19 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_postview_postvn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
