# Generated by Django 4.1.2 on 2022-10-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='transaction',
            field=models.CharField(choices=[('1', 'IN'), ('2', 'OUT')], max_length=20),
        ),
    ]
